# Auto-generated by /Users/lekangzoukang/git/nipype2pydra/nipype2pydra/package.py, do not edit as it will be overwritten

src_pkg_version = "23.2.0"
nipype2pydra_version = "0.3.6"
post_release = "2320036"
        